sudo: required
language: node_js
node_js: '8'
git:
  depth: 1
cache:
  yarn: true
  directories:
  - samples/code-lens-provider-plugin/node_modules
  - node_modules
branches:
  only:
  - master
env:
  global:
    - NODE_OPTIONS="--max_old_space_size=4096"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
  - export PATH=$HOME/.yarn/bin:$PATH ;
install: yarn
script: travis_retry yarn;
jobs:
  fast_finish: true
  include:
  - stage: build
    install: skip
    before_script: skip
    script: travis_retry yarn;
